/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basics;

import java.io.IOException;
import java.nio.file.Path;
import java.util.Arrays;
import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws IOException {
        System.out.println("command line arguments: " + Arrays.toString(args));
        System.out.println(System.getProperty("user.dir"));
    }

    public static void lintFile(String fileToBeRead) throws IOException {
        Path fileToBeLinted = Path.of(fileToBeRead);
        int lineNumber = 0;
        String errorMessage = "";
        try (Scanner fileScanner = new Scanner(fileToBeLinted)) {
            while (fileScanner.hasNextLine()) {
                errorMessage = "";
                String currentLine = fileScanner.nextLine();
                lineNumber++;
                if (!currentLine.endsWith(";")) {
                    if (currentLine.isEmpty() || currentLine.endsWith("{") || currentLine.endsWith("}") || currentLine.contains("if") || currentLine.contains("else")) {
                    } else {
                        errorMessage += "Line: " + lineNumber + ": Missing semicolon.\n";
                        System.out.println(errorMessage);

                    }
                }

            }
        } catch (IOException ioe) {
            ioe.printStackTrace();
        }

    }
}

