/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.jupiter.api.Test;

import java.util.ListResourceBundle;

import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    // Daily average temperatures for Seattle, October 1-28 2017
    int[][] weeklyMonthTemperatures = {
            {66, 64, 58, 65, 71, 57, 60},
            {57, 65, 65, 70, 72, 65, 51},
            {55, 54, 60, 53, 59, 57, 61},
            {65, 56, 55, 52, 55, 62, 57}
    };

    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
    @Test void testThisTest(){
        Library sut = new Library();
        String actual = sut.analyzeData(weeklyMonthTemperatures);
        assertTrue(actual.equals("""
                High: 72
                Low: 51
                Never saw temperature: 63
                Never saw temperature: 67
                Never saw temperature: 68
                Never saw temperature: 69
                """));
    }
}
