/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import java.util.HashSet;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    public String analyzeData(int[][] weatherData){
        String output = "";
        HashSet<Integer> temperatureSet = new HashSet<>();
        int min = weatherData[0][0];
        int max = weatherData[0][0];
        for (int i = 0; i < weatherData.length; i++) {
            for (int j = 0; j < weatherData[i].length; j++){
            if (weatherData[i][j] > max)
                max = weatherData[i][j];
            if (weatherData[i][j] < min)
                min = weatherData[i][j];
            temperatureSet.add(weatherData[i][j]);
            }
        }
        for (int i = min; i <= max; i++) {
            if (temperatureSet.contains(i))
                output = i + " ";
        }
        return output;
    }

//    public static String tally(List<arr>) {
//        HashMap<String, Integer> votes = new HashMap<>();
//        int numVotes = 0;
//        String elected = "";
//        for (string vote : arr) {
//            if (votes.containsKey(vote)) {
//                votes.put(vote, votes.get(vote) + 1);
//            } else {
//                votes.put(vote,1);
//            } for (String candidate : arr) {
//                if(votes.get(vote) > numVotes) {
//                    numVotes = votes.get(vote);
//                    elected = vote;
//                }
//            }
//        }
//        return elected;
//    }
}
